cabal-version: 3.0
name: wic-cli
version: 0.1.0.0
synopsis: UNM Women in Computing - Job & Internship CLI

common shared-deps
  build-depends:
      base >= 4.14 && < 5
    , text >= 1.2
    , time >= 1.9
    , containers >= 0.6
    , http-conduit >= 2.3
    , scalpel >= 0.6
    , aeson >= 2.0
    , bytestring >= 0.11
    , directory >= 1.3

executable wic-cli
  import: shared-deps
  hs-source-dirs: src
  main-is: Main.hs
  other-modules:
      Types
    , Scraper
    , Search
    , Filter
    , Recommend
    , Deadline
    , Display
  default-language: Haskell2010